Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
  # myEc2Instance:
  #   Type: AWS::EC2:Instance
  #   Properties:
  #     ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 32 ]
  #     InstanceType: m1.small
  #AWS::Region = Pseudo Parameter

Mappings:
  RegionMap:
    us-east-1:
      "32": "ami-6411e20d"
      "64": "ami-7a11e213"
    us-west-1:
      "32": "ami-c9c7978c"
      "64": "ami-cfc7978a"
#To Get any param = !FindInMap [MapName, TopLevel, SecondLevel]

# Condition
# Resources:
#   ConditionInstance:
#     Type: AWS::EC2::Instance
#     Condition: ViniConditionDemo  ##base on this, create or not de EC2 instance
#     Properties:
#       AvailabilityZone: us-east-1a
#       ImageId: ami-a4c7edb2
#       InstanceType: t2.micro

# Conditions:
#   ViniConditionDemo:
#     !Equals ['true', 'true']  ##Return TRUE OR FALSE

# JOIN COMMAND
# !Join [ delimiter , [objects to be joined] ]
# !Join[':', [a,b,c]] = 'a:b:c'