Tranform Header indicates it's SAM tamplate
  Transform: 'AWS::Servaless-2016-10-31'

to write code
'AWS::Serverless::Function' FOR LAMBDA
'AWS::Serverless::Api' FOR API GATEWAY
'AWS::Serverless::SimpleTable' FOR DYNAMODB

to prackage & deploy
to aws cloudformation package / sam package
to aws cloudformation deploy / sam deploy

EX:
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda Function
Resources:
  # CREATE LAMBDA
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Description: A starter AWS Lambda function
      MemorySize: 128
      Timeout: 3
      # INSTANTIATE DYNAMODB
      Enviroment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Events:
        # CREATE API GATEWAY 
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      # ADD POLICY TO CALL DYNAMO
      Policies:
        - DynamoDBCrudPolicy:
          TableName: !Ref Table
  # CREATE DYNAMODB
  Table:
    Type: 'AWS::Serverless::SimpleTable'
    Propreties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1